server:
  port: 8002

spring:
  application:
    name: spring-message-rocketmq-producer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

rocketmq:
  name-server: 10.211.55.3:9876
  producer:
    group: define-group
