server:
  port: 8002

spring:
  application:
    name: spring-distributed-lock
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.71.128
    port: 6379
    database: 0
  cache:
    type: redis
