server:
  port: 8002

spring:
  application:
    name: spring-distributed-session
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.128:3306/orders?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: FN5HW5Y1XQJ742I7
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities
